name: Build and Deploy Node.js Application

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      #   - run: npm test

      - name: Build and push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build . -t ghcr.io/${REPO_NAME}:latest
          docker push ghcr.io/${REPO_NAME}:latest

      - name: Install Railway
        run: npm i -g @railway/cli

      #   # TODO make it dynamic
      # - name: Deploy
      #   run: railway up --service b47f7009-a753-4ecc-a05f-1978fb96c136
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
